### PR TITLE
Make tests pass on newer click (>=7.1.2)

### PR DESCRIPTION
**Pull request by frantisekz**
Used downstream in Fedora: https://src.fedoraproject.org/rpms/python-click-didyoumean/blob/master/f/0001-Fix-tests-some-more.patch

### CODE REVIEW

**Comment by timofurrer** [comment]
Looks good :tada: Can you adapt the unit tests to match the change?

**Comment by frantisekz** [comment]
> Looks good  Can you adapt the unit tests to match the change?

Should be all good? I assume you've meant to change tested python versions? I was changing unit tests only :)

**Comment by timofurrer** [comment]
Thanks! Yes, that's what I meant ;)

**Comment by frantisekz** [comment]
Thanks a lot!

**Pull request merged**
